spring.application.name=ControlCamiones

spring.datasource.url=jdbc:postgresql://177.7.48.25:5432/CamionesBD
spring.datasource.username=sistema
spring.datasource.password=Control@dmin2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect